# Conda environment file with direct project dependencies without secondary dependencies.
# Won't probably work out of the box. First try the *_exported.yml version.
#
# create a new environment:
#   conda env create -f conda_gui.yml
#
#   or when specific python version is required:
#
#   conda create -n ferda_gui python=3.9  # need to be separated to multiple steps,
#                                         # see https://github.com/conda/conda/issues/4756
#   conda activate ferda_gui
#   conda env update -f conda_gui.yml
#
name: ferda_gui
channels: 
    - conda-forge
dependencies:
#  - ffmpeg
  - graph-tool
  - pip
  - pip:
    - -r requirements.txt
