# use: conda env create -f conda.yml
name: ferda
channels: 
    - conda-forge
    - ostrokach-forge  # graph-tool
dependencies:
  - python=2.7
  - imageio
  - pyqt=4
  - pyyaml
  - opencv
  - scikit-image
  - pip:
    - matplotlib
    - pyqtgraph
    - pympler
    - qimage2ndarray
    - lazyme
    - cachetools
    - imutils
    - joblib
  - scikit-learn
  - tqdm
  - pandas
  - h5py
  - fire
  - numpy
  - graph-tool
  - keras
#  - future

