general:
    log_graph_edits: true
    log_in_bg_computation: false  # Could be switched off before user interactions to save space.
    print_log: true

cache:
    use: true # There will be stored information in working directory to speed up mainly the results tool.
    mser: true # Storing MSERs have huge impact on speed but it also needs huge space amount.
    img_manager_size_MB: 500
    region_manager_num_of_instances: 0

#colormarks:
#    mser_max_area: 200  # Used in colormark detection process to ignore all regions bigger then this parameter (in pixels)
#    mser_min_area: 5  # Used in colormark detection process to ignore all regions lower then this parameter (in pixels)
#    mser_min_margin: 5  # Used in colormark detection process to ignore all regions with margin (stability) lower then this parameter
#    avg_radius: 10  # is automatically set by algorithm, you should not modify this value...
#    debug: true  # More values will be stored for easier debug...
#    igbr_i_norm: 2298  # (255*3 + 1) * 3
#    igbr_i_weight: 0.5

parallelization:
    processes_num: -1  # The number of processes. It is good idea to set it <= num of CPUs. If negative cpu_count() - processes_num.
    use: true
    frames_in_row: 100  # num of frames in one part into which the whole video is divided..
