general:
    log_graph_edits: false
    log_in_bg_computation: false  # Could be switched off before user interactions to save space.
    print_log: true
    fix_random_seed: false  # fix randomization seed for reproducibility (not yet supported everywhere)
    n_jobs: 15  # number of jobs to run in parallel, if -1 all CPUs are used,
                # see https://pythonhosted.org/joblib/parallel.html#parallel-reference-documentation

cache:
    use: true # There will be stored information in working directory to speed up mainly the results tool.
    mser: true # Storing MSERs have huge impact on speed but it also needs huge space amount.
    img_manager_size_MB: 500

region_classifier:
    samples_preselection_num: 1000
    samples_num: 100
    default_features: ['area', 'major axis length', 'minor axis length', 'contour length']

segmentation:
    frames_in_row: 100
