# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ants_init.ui'
#
# Created: Wed Oct 15 16:59:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(716, 616)
        Dialog.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 311, 617))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_viedo_source = QtGui.QWidget()
        self.tab_viedo_source.setObjectName(_fromUtf8("tab_viedo_source"))
        self.video_group = QtGui.QGroupBox(self.tab_viedo_source)
        self.video_group.setGeometry(QtCore.QRect(10, 10, 271, 321))
        self.video_group.setMinimumSize(QtCore.QSize(251, 111))
        self.video_group.setAutoFillBackground(False)
        self.video_group.setFlat(False)
        self.video_group.setCheckable(False)
        self.video_group.setObjectName(_fromUtf8("video_group"))
        self.file_name_label = QtGui.QLabel(self.video_group)
        self.file_name_label.setGeometry(QtCore.QRect(3, 23, 261, 14))
        self.file_name_label.setObjectName(_fromUtf8("file_name_label"))
        self.b_choose_video = QtGui.QPushButton(self.video_group)
        self.b_choose_video.setGeometry(QtCore.QRect(0, 41, 141, 30))
        self.b_choose_video.setObjectName(_fromUtf8("b_choose_video"))
        self.ch_invert_image = QtGui.QCheckBox(self.video_group)
        self.ch_invert_image.setEnabled(False)
        self.ch_invert_image.setGeometry(QtCore.QRect(2, 100, 110, 20))
        self.ch_invert_image.setChecked(False)
        self.ch_invert_image.setObjectName(_fromUtf8("ch_invert_image"))
        self.b_load_video = QtGui.QPushButton(self.video_group)
        self.b_load_video.setEnabled(False)
        self.b_load_video.setGeometry(QtCore.QRect(150, 42, 110, 27))
        self.b_load_video.setObjectName(_fromUtf8("b_load_video"))
        self.b_video_continue = QtGui.QPushButton(self.video_group)
        self.b_video_continue.setEnabled(False)
        self.b_video_continue.setGeometry(QtCore.QRect(134, 280, 120, 27))
        self.b_video_continue.setObjectName(_fromUtf8("b_video_continue"))
        self.label_5 = QtGui.QLabel(self.video_group)
        self.label_5.setGeometry(QtCore.QRect(5, 80, 258, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.b_count_bg_model = QtGui.QPushButton(self.video_group)
        self.b_count_bg_model.setEnabled(False)
        self.b_count_bg_model.setGeometry(QtCore.QRect(3, 220, 250, 27))
        self.b_count_bg_model.setObjectName(_fromUtf8("b_count_bg_model"))
        self.b_use_model = QtGui.QPushButton(self.video_group)
        self.b_use_model.setEnabled(False)
        self.b_use_model.setGeometry(QtCore.QRect(4, 280, 120, 27))
        self.b_use_model.setObjectName(_fromUtf8("b_use_model"))
        self.spin_bg_num_steps = QtGui.QSpinBox(self.video_group)
        self.spin_bg_num_steps.setGeometry(QtCore.QRect(190, 190, 60, 27))
        self.spin_bg_num_steps.setMinimum(1)
        self.spin_bg_num_steps.setMaximum(1000)
        self.spin_bg_num_steps.setProperty("value", 20)
        self.spin_bg_num_steps.setObjectName(_fromUtf8("spin_bg_num_steps"))
        self.label_7 = QtGui.QLabel(self.video_group)
        self.label_7.setGeometry(QtCore.QRect(69, 193, 111, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.video_group)
        self.label_8.setGeometry(QtCore.QRect(70, 160, 111, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spin_bg_step_length = QtGui.QSpinBox(self.video_group)
        self.spin_bg_step_length.setGeometry(QtCore.QRect(190, 157, 60, 27))
        self.spin_bg_step_length.setMinimum(1)
        self.spin_bg_step_length.setMaximum(10000)
        self.spin_bg_step_length.setProperty("value", 50)
        self.spin_bg_step_length.setObjectName(_fromUtf8("spin_bg_step_length"))
        self.b_model_fix_tool = QtGui.QPushButton(self.video_group)
        self.b_model_fix_tool.setEnabled(False)
        self.b_model_fix_tool.setGeometry(QtCore.QRect(3, 250, 250, 27))
        self.b_model_fix_tool.setObjectName(_fromUtf8("b_model_fix_tool"))
        self.tabWidget.addTab(self.tab_viedo_source, _fromUtf8(""))
        self.tab_arena = QtGui.QWidget()
        self.tab_arena.setObjectName(_fromUtf8("tab_arena"))
        self.arena_group = QtGui.QGroupBox(self.tab_arena)
        self.arena_group.setEnabled(False)
        self.arena_group.setGeometry(QtCore.QRect(10, 10, 291, 261))
        self.arena_group.setMinimumSize(QtCore.QSize(251, 111))
        self.arena_group.setAutoFillBackground(False)
        self.arena_group.setFlat(False)
        self.arena_group.setCheckable(False)
        self.arena_group.setObjectName(_fromUtf8("arena_group"))
        self.b_continue_arena = QtGui.QPushButton(self.arena_group)
        self.b_continue_arena.setGeometry(QtCore.QRect(120, 220, 161, 27))
        self.b_continue_arena.setObjectName(_fromUtf8("b_continue_arena"))
        self.sb_arena_shape = QtGui.QComboBox(self.arena_group)
        self.sb_arena_shape.setGeometry(QtCore.QRect(75, 20, 181, 27))
        self.sb_arena_shape.setObjectName(_fromUtf8("sb_arena_shape"))
        self.sb_arena_shape.addItem(_fromUtf8(""))
        self.sb_arena_shape.addItem(_fromUtf8(""))
        self.sb_arena_shape.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.arena_group)
        self.label_9.setGeometry(QtCore.QRect(5, 23, 61, 20))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tableWidget = QtGui.QTableWidget(self.arena_group)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 256, 161))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab_arena, _fromUtf8(""))
        self.tab_objects = QtGui.QWidget()
        self.tab_objects.setObjectName(_fromUtf8("tab_objects"))
        self.ants_group = QtGui.QGroupBox(self.tab_objects)
        self.ants_group.setEnabled(False)
        self.ants_group.setGeometry(QtCore.QRect(10, 10, 271, 231))
        self.ants_group.setObjectName(_fromUtf8("ants_group"))
        self.label_4 = QtGui.QLabel(self.ants_group)
        self.label_4.setGeometry(QtCore.QRect(15, 25, 130, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ant_number_spin_box = QtGui.QSpinBox(self.ants_group)
        self.ant_number_spin_box.setGeometry(QtCore.QRect(150, 20, 61, 27))
        self.ant_number_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ant_number_spin_box.setKeyboardTracking(True)
        self.ant_number_spin_box.setMinimum(1)
        self.ant_number_spin_box.setMaximum(100)
        self.ant_number_spin_box.setProperty("value", 15)
        self.ant_number_spin_box.setObjectName(_fromUtf8("ant_number_spin_box"))
        self.b_continue_ants = QtGui.QPushButton(self.ants_group)
        self.b_continue_ants.setGeometry(QtCore.QRect(100, 50, 161, 27))
        self.b_continue_ants.setObjectName(_fromUtf8("b_continue_ants"))
        self.label_6 = QtGui.QLabel(self.ants_group)
        self.label_6.setGeometry(QtCore.QRect(15, 90, 241, 141))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget.addTab(self.tab_objects, _fromUtf8(""))
        self.tab_object_selection = QtGui.QWidget()
        self.tab_object_selection.setEnabled(False)
        self.tab_object_selection.setObjectName(_fromUtf8("tab_object_selection"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_object_selection)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 301, 581))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(3, 3, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.scrollArea = QtGui.QScrollArea(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.object_init_layout = QtGui.QVBoxLayout()
        self.object_init_layout.setSpacing(1)
        self.object_init_layout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.object_init_layout.setObjectName(_fromUtf8("object_init_layout"))
        self.verticalLayout.addLayout(self.object_init_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.scrollArea_2 = QtGui.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.init_mser_grid = QtGui.QGridLayout()
        self.init_mser_grid.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.init_mser_grid.setSpacing(0)
        self.init_mser_grid.setObjectName(_fromUtf8("init_mser_grid"))
        self.verticalLayout_2.addLayout(self.init_mser_grid)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.start_button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.verticalLayout_3.addWidget(self.start_button)
        self.tabWidget.addTab(self.tab_object_selection, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "experiment settings", None))
        self.video_group.setTitle(_translate("Dialog", "Video source", None))
        self.file_name_label.setText(_translate("Dialog", "source path...", None))
        self.b_choose_video.setText(_translate("Dialog", "choose video file", None))
        self.ch_invert_image.setText(_translate("Dialog", "invert image", None))
        self.b_load_video.setText(_translate("Dialog", "load", None))
        self.b_video_continue.setText(_translate("Dialog", "without model", None))
        self.label_5.setText(_translate("Dialog", "if objects are light on dark background", None))
        self.b_count_bg_model.setText(_translate("Dialog", "count bg model (optional)", None))
        self.b_use_model.setText(_translate("Dialog", "use model", None))
        self.label_7.setText(_translate("Dialog", "num of steps:", None))
        self.label_8.setText(_translate("Dialog", "step length:", None))
        self.b_model_fix_tool.setText(_translate("Dialog", "model fix tool", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viedo_source), _translate("Dialog", "Video source", None))
        self.arena_group.setTitle(_translate("Dialog", "Arena", None))
        self.b_continue_arena.setText(_translate("Dialog", "confirm and continue", None))
        self.sb_arena_shape.setItemText(0, _translate("Dialog", "circle", None))
        self.sb_arena_shape.setItemText(1, _translate("Dialog", "ellipse", None))
        self.sb_arena_shape.setItemText(2, _translate("Dialog", "polygon", None))
        self.label_9.setText(_translate("Dialog", "shape:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arena), _translate("Dialog", "Arena", None))
        self.ants_group.setTitle(_translate("Dialog", "Tracked objects", None))
        self.label_4.setText(_translate("Dialog", "Number of objects", None))
        self.b_continue_ants.setText(_translate("Dialog", "confirm and continue", None))
        self.label_6.setText(_translate("Dialog", "Now assign ants to the regions.  Assignment can be done by clicking on button in ant sellection and then by clicking on region in image collection window. When ant is assigned to the region, the region in window collections changes the color.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_objects), _translate("Dialog", "Objects", None))
        self.label.setText(_translate("Dialog", "Objects selection", None))
        self.start_button.setText(_translate("Dialog", "confirm and start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_object_selection), _translate("Dialog", "Selection", None))

