# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ants_view.ui'
#
# Created: Sat Mar 15 12:07:48 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(350, 301)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 320, 80))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.b_play = QtGui.QPushButton(self.groupBox_2)
        self.b_play.setGeometry(QtCore.QRect(0, 20, 90, 27))
        self.b_play.setObjectName(_fromUtf8("b_play"))
        self.b_backwards = QtGui.QPushButton(self.groupBox_2)
        self.b_backwards.setGeometry(QtCore.QRect(110, 20, 101, 27))
        self.b_backwards.setObjectName(_fromUtf8("b_backwards"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(218, 0, 61, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.l_frame = QtGui.QLabel(self.groupBox_2)
        self.l_frame.setGeometry(QtCore.QRect(275, 0, 31, 17))
        self.l_frame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_frame.setObjectName(_fromUtf8("l_frame"))
        self.b_forwards = QtGui.QPushButton(self.groupBox_2)
        self.b_forwards.setGeometry(QtCore.QRect(210, 20, 98, 27))
        self.b_forwards.setObjectName(_fromUtf8("b_forwards"))
        self.sb_stop_at_frame = QtGui.QSpinBox(self.groupBox_2)
        self.sb_stop_at_frame.setGeometry(QtCore.QRect(110, 50, 60, 27))
        self.sb_stop_at_frame.setMaximum(999999999)
        self.sb_stop_at_frame.setObjectName(_fromUtf8("sb_stop_at_frame"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 55, 121, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(110, 0, 91, 17))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 350, 209))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.ch_mser_collection = QtGui.QCheckBox(self.tab)
        self.ch_mser_collection.setGeometry(QtCore.QRect(10, 10, 201, 22))
        self.ch_mser_collection.setChecked(False)
        self.ch_mser_collection.setObjectName(_fromUtf8("ch_mser_collection"))
        self.ch_ants_collection = QtGui.QCheckBox(self.tab)
        self.ch_ants_collection.setGeometry(QtCore.QRect(10, 30, 161, 22))
        self.ch_ants_collection.setChecked(True)
        self.ch_ants_collection.setObjectName(_fromUtf8("ch_ants_collection"))
        self.imshow_decreasing_factor = QtGui.QDoubleSpinBox(self.tab)
        self.imshow_decreasing_factor.setGeometry(QtCore.QRect(160, 49, 60, 27))
        self.imshow_decreasing_factor.setMinimum(0.25)
        self.imshow_decreasing_factor.setMaximum(1.0)
        self.imshow_decreasing_factor.setSingleStep(0.05)
        self.imshow_decreasing_factor.setProperty("value", 0.5)
        self.imshow_decreasing_factor.setObjectName(_fromUtf8("imshow_decreasing_factor"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(14, 54, 151, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.ch_log_each_frame = QtGui.QCheckBox(self.tab_2)
        self.ch_log_each_frame.setGeometry(QtCore.QRect(10, 10, 201, 22))
        self.ch_log_each_frame.setChecked(False)
        self.ch_log_each_frame.setObjectName(_fromUtf8("ch_log_each_frame"))
        self.ch_log_verbose = QtGui.QCheckBox(self.tab_2)
        self.ch_log_verbose.setGeometry(QtCore.QRect(10, 30, 161, 22))
        self.ch_log_verbose.setChecked(False)
        self.ch_log_verbose.setObjectName(_fromUtf8("ch_log_verbose"))
        self.b_log_save_regions = QtGui.QPushButton(self.tab_2)
        self.b_log_save_regions.setGeometry(QtCore.QRect(10, 71, 100, 27))
        self.b_log_save_regions.setObjectName(_fromUtf8("b_log_save_regions"))
        self.b_log_save_regions_collection = QtGui.QPushButton(self.tab_2)
        self.b_log_save_regions_collection.setGeometry(QtCore.QRect(110, 71, 150, 27))
        self.b_log_save_regions_collection.setObjectName(_fromUtf8("b_log_save_regions_collection"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(11, 56, 70, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.b_log_save_frame = QtGui.QPushButton(self.tab_2)
        self.b_log_save_frame.setGeometry(QtCore.QRect(10, 98, 100, 27))
        self.b_log_save_frame.setObjectName(_fromUtf8("b_log_save_frame"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.b_save_file = QtGui.QPushButton(self.tab_4)
        self.b_save_file.setGeometry(QtCore.QRect(280, 30, 61, 27))
        self.b_save_file.setObjectName(_fromUtf8("b_save_file"))
        self.b_choose_path = QtGui.QPushButton(self.tab_4)
        self.b_choose_path.setGeometry(QtCore.QRect(8, 30, 100, 27))
        self.b_choose_path.setObjectName(_fromUtf8("b_choose_path"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(244, 35, 40, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.i_file_name = QtGui.QLineEdit(self.tab_4)
        self.i_file_name.setGeometry(QtCore.QRect(110, 30, 131, 27))
        self.i_file_name.setObjectName(_fromUtf8("i_file_name"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 341, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 65, 341, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.i_state_name = QtGui.QLineEdit(self.tab_4)
        self.i_state_name.setGeometry(QtCore.QRect(110, 85, 131, 27))
        self.i_state_name.setObjectName(_fromUtf8("i_state_name"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(244, 90, 30, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.b_choose_path_state = QtGui.QPushButton(self.tab_4)
        self.b_choose_path_state.setGeometry(QtCore.QRect(8, 85, 100, 27))
        self.b_choose_path_state.setObjectName(_fromUtf8("b_choose_path_state"))
        self.b_save_state = QtGui.QPushButton(self.tab_4)
        self.b_save_state.setGeometry(QtCore.QRect(280, 84, 61, 27))
        self.b_save_state.setObjectName(_fromUtf8("b_save_state"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 320, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.b_load_state = QtGui.QPushButton(self.tab_4)
        self.b_load_state.setGeometry(QtCore.QRect(10, 139, 61, 27))
        self.b_load_state.setObjectName(_fromUtf8("b_load_state"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "experiment controls", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.b_play.setText(QtGui.QApplication.translate("Dialog", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.b_backwards.setText(QtGui.QApplication.translate("Dialog", "< backwards", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "frame #:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_frame.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.b_forwards.setText(QtGui.QApplication.translate("Dialog", "forwards >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "run until frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_mser_collection.setText(QtGui.QApplication.translate("Dialog", "msers collection", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_ants_collection.setText(QtGui.QApplication.translate("Dialog", "ants collection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "img size (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "display", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_log_each_frame.setText(QtGui.QApplication.translate("Dialog", "each frame", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_log_verbose.setText(QtGui.QApplication.translate("Dialog", "verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.b_log_save_regions.setText(QtGui.QApplication.translate("Dialog", "regions info", None, QtGui.QApplication.UnicodeUTF8))
        self.b_log_save_regions_collection.setText(QtGui.QApplication.translate("Dialog", "regions collection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "save:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_log_save_frame.setText(QtGui.QApplication.translate("Dialog", "frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.b_save_file.setText(QtGui.QApplication.translate("Dialog", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.b_choose_path.setText(QtGui.QApplication.translate("Dialog", "choose path", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", ".mat", None, QtGui.QApplication.UnicodeUTF8))
        self.i_file_name.setText(QtGui.QApplication.translate("Dialog", "mat_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Save results to .mat file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Save Ferda\'s state:", None, QtGui.QApplication.UnicodeUTF8))
        self.i_state_name.setText(QtGui.QApplication.translate("Dialog", "checkpoin_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", ".plk", None, QtGui.QApplication.UnicodeUTF8))
        self.b_choose_path_state.setText(QtGui.QApplication.translate("Dialog", "choose path", None, QtGui.QApplication.UnicodeUTF8))
        self.b_save_state.setText(QtGui.QApplication.translate("Dialog", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Load Ferda\'s state:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_load_state.setText(QtGui.QApplication.translate("Dialog", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "state", None, QtGui.QApplication.UnicodeUTF8))

