# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ants_view.ui'
#
# Created: Thu Jun 26 18:48:46 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(350, 301)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 320, 80))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.b_play = QtGui.QPushButton(self.groupBox_2)
        self.b_play.setGeometry(QtCore.QRect(0, 20, 90, 27))
        self.b_play.setObjectName(_fromUtf8("b_play"))
        self.b_backwards = QtGui.QPushButton(self.groupBox_2)
        self.b_backwards.setGeometry(QtCore.QRect(110, 20, 101, 27))
        self.b_backwards.setObjectName(_fromUtf8("b_backwards"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(212, 0, 61, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.l_frame = QtGui.QLabel(self.groupBox_2)
        self.l_frame.setGeometry(QtCore.QRect(274, 0, 33, 17))
        self.l_frame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_frame.setObjectName(_fromUtf8("l_frame"))
        self.b_forwards = QtGui.QPushButton(self.groupBox_2)
        self.b_forwards.setGeometry(QtCore.QRect(210, 20, 98, 27))
        self.b_forwards.setObjectName(_fromUtf8("b_forwards"))
        self.sb_stop_at_frame = QtGui.QSpinBox(self.groupBox_2)
        self.sb_stop_at_frame.setGeometry(QtCore.QRect(110, 50, 60, 27))
        self.sb_stop_at_frame.setMaximum(999999999)
        self.sb_stop_at_frame.setObjectName(_fromUtf8("sb_stop_at_frame"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 55, 121, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(110, 0, 91, 17))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 350, 209))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.ch_mser_collection = QtGui.QCheckBox(self.tab)
        self.ch_mser_collection.setGeometry(QtCore.QRect(10, 10, 201, 22))
        self.ch_mser_collection.setChecked(False)
        self.ch_mser_collection.setObjectName(_fromUtf8("ch_mser_collection"))
        self.ch_ants_collection = QtGui.QCheckBox(self.tab)
        self.ch_ants_collection.setEnabled(True)
        self.ch_ants_collection.setGeometry(QtCore.QRect(10, 30, 161, 22))
        self.ch_ants_collection.setChecked(True)
        self.ch_ants_collection.setObjectName(_fromUtf8("ch_ants_collection"))
        self.imshow_decreasing_factor = QtGui.QDoubleSpinBox(self.tab)
        self.imshow_decreasing_factor.setGeometry(QtCore.QRect(110, 80, 60, 27))
        self.imshow_decreasing_factor.setMinimum(0.25)
        self.imshow_decreasing_factor.setMaximum(1.0)
        self.imshow_decreasing_factor.setSingleStep(0.05)
        self.imshow_decreasing_factor.setProperty("value", 0.5)
        self.imshow_decreasing_factor.setObjectName(_fromUtf8("imshow_decreasing_factor"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(14, 85, 91, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ch_print_mser_info = QtGui.QCheckBox(self.tab)
        self.ch_print_mser_info.setGeometry(QtCore.QRect(180, 10, 161, 22))
        self.ch_print_mser_info.setChecked(False)
        self.ch_print_mser_info.setObjectName(_fromUtf8("ch_print_mser_info"))
        self.ch_imshow = QtGui.QCheckBox(self.tab)
        self.ch_imshow.setGeometry(QtCore.QRect(180, 30, 161, 22))
        self.ch_imshow.setChecked(True)
        self.ch_imshow.setObjectName(_fromUtf8("ch_imshow"))
        self.ch_assignment_problem = QtGui.QCheckBox(self.tab)
        self.ch_assignment_problem.setGeometry(QtCore.QRect(10, 50, 161, 22))
        self.ch_assignment_problem.setChecked(False)
        self.ch_assignment_problem.setObjectName(_fromUtf8("ch_assignment_problem"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.ch_log_each_frame = QtGui.QCheckBox(self.tab_2)
        self.ch_log_each_frame.setEnabled(False)
        self.ch_log_each_frame.setGeometry(QtCore.QRect(10, 10, 201, 22))
        self.ch_log_each_frame.setChecked(False)
        self.ch_log_each_frame.setObjectName(_fromUtf8("ch_log_each_frame"))
        self.ch_log_verbose = QtGui.QCheckBox(self.tab_2)
        self.ch_log_verbose.setEnabled(False)
        self.ch_log_verbose.setGeometry(QtCore.QRect(10, 30, 161, 22))
        self.ch_log_verbose.setChecked(False)
        self.ch_log_verbose.setObjectName(_fromUtf8("ch_log_verbose"))
        self.b_log_save_regions = QtGui.QPushButton(self.tab_2)
        self.b_log_save_regions.setEnabled(False)
        self.b_log_save_regions.setGeometry(QtCore.QRect(10, 71, 100, 27))
        self.b_log_save_regions.setObjectName(_fromUtf8("b_log_save_regions"))
        self.b_log_save_regions_collection = QtGui.QPushButton(self.tab_2)
        self.b_log_save_regions_collection.setEnabled(False)
        self.b_log_save_regions_collection.setGeometry(QtCore.QRect(110, 71, 150, 27))
        self.b_log_save_regions_collection.setObjectName(_fromUtf8("b_log_save_regions_collection"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(11, 56, 70, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.b_log_save_frame = QtGui.QPushButton(self.tab_2)
        self.b_log_save_frame.setEnabled(False)
        self.b_log_save_frame.setGeometry(QtCore.QRect(10, 98, 100, 27))
        self.b_log_save_frame.setObjectName(_fromUtf8("b_log_save_frame"))
        self.b_log_all = QtGui.QPushButton(self.tab_2)
        self.b_log_all.setEnabled(False)
        self.b_log_all.setGeometry(QtCore.QRect(110, 140, 98, 27))
        self.b_log_all.setObjectName(_fromUtf8("b_log_all"))
        self.b_log_assignment_problem = QtGui.QPushButton(self.tab_2)
        self.b_log_assignment_problem.setEnabled(False)
        self.b_log_assignment_problem.setGeometry(QtCore.QRect(110, 99, 150, 27))
        self.b_log_assignment_problem.setObjectName(_fromUtf8("b_log_assignment_problem"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.b_save_file = QtGui.QPushButton(self.tab_4)
        self.b_save_file.setGeometry(QtCore.QRect(280, 30, 61, 27))
        self.b_save_file.setObjectName(_fromUtf8("b_save_file"))
        self.b_choose_path = QtGui.QPushButton(self.tab_4)
        self.b_choose_path.setGeometry(QtCore.QRect(8, 30, 100, 27))
        self.b_choose_path.setObjectName(_fromUtf8("b_choose_path"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(244, 35, 40, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.i_file_name = QtGui.QLineEdit(self.tab_4)
        self.i_file_name.setGeometry(QtCore.QRect(110, 30, 131, 27))
        self.i_file_name.setObjectName(_fromUtf8("i_file_name"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 341, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 65, 341, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.i_state_name = QtGui.QLineEdit(self.tab_4)
        self.i_state_name.setGeometry(QtCore.QRect(110, 85, 131, 27))
        self.i_state_name.setObjectName(_fromUtf8("i_state_name"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(244, 90, 30, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.b_choose_path_state = QtGui.QPushButton(self.tab_4)
        self.b_choose_path_state.setGeometry(QtCore.QRect(8, 85, 100, 27))
        self.b_choose_path_state.setObjectName(_fromUtf8("b_choose_path_state"))
        self.b_save_state = QtGui.QPushButton(self.tab_4)
        self.b_save_state.setGeometry(QtCore.QRect(280, 84, 61, 27))
        self.b_save_state.setObjectName(_fromUtf8("b_save_state"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 320, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.b_load_state = QtGui.QPushButton(self.tab_4)
        self.b_load_state.setGeometry(QtCore.QRect(10, 139, 61, 27))
        self.b_load_state.setObjectName(_fromUtf8("b_load_state"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.label_11 = QtGui.QLabel(self.info)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.info)
        self.label_12.setGeometry(QtCore.QRect(0, 16, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.info)
        self.label_13.setGeometry(QtCore.QRect(0, 32, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.l_avg_a_area = QtGui.QLabel(self.info)
        self.l_avg_a_area.setGeometry(QtCore.QRect(103, 1, 66, 17))
        self.l_avg_a_area.setObjectName(_fromUtf8("l_avg_a_area"))
        self.l_avg_a_a = QtGui.QLabel(self.info)
        self.l_avg_a_a.setGeometry(QtCore.QRect(103, 17, 66, 17))
        self.l_avg_a_a.setObjectName(_fromUtf8("l_avg_a_a"))
        self.l_mser_thresh = QtGui.QLabel(self.info)
        self.l_mser_thresh.setGeometry(QtCore.QRect(103, 33, 55, 17))
        self.l_mser_thresh.setObjectName(_fromUtf8("l_mser_thresh"))
        self.tabWidget.addTab(self.info, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "experiment controls", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Controls", None))
        self.b_play.setText(_translate("Dialog", "play", None))
        self.b_backwards.setText(_translate("Dialog", "< backwards", None))
        self.label_2.setText(_translate("Dialog", "frame #:", None))
        self.l_frame.setText(_translate("Dialog", "1", None))
        self.b_forwards.setText(_translate("Dialog", "forwards >", None))
        self.label_8.setText(_translate("Dialog", "run until frame:", None))
        self.ch_mser_collection.setText(_translate("Dialog", "msers collection", None))
        self.ch_ants_collection.setText(_translate("Dialog", "ants collection", None))
        self.label_4.setText(_translate("Dialog", "img size (%)", None))
        self.ch_print_mser_info.setText(_translate("Dialog", "print mser info", None))
        self.ch_imshow.setText(_translate("Dialog", "imshow", None))
        self.ch_assignment_problem.setText(_translate("Dialog", "assignment problem", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "display", None))
        self.ch_log_each_frame.setText(_translate("Dialog", "each frame", None))
        self.ch_log_verbose.setText(_translate("Dialog", "verbose", None))
        self.b_log_save_regions.setText(_translate("Dialog", "regions info", None))
        self.b_log_save_regions_collection.setText(_translate("Dialog", "regions collection", None))
        self.label_5.setText(_translate("Dialog", "save:", None))
        self.b_log_save_frame.setText(_translate("Dialog", "frame", None))
        self.b_log_all.setText(_translate("Dialog", "all", None))
        self.b_log_assignment_problem.setText(_translate("Dialog", "assignment problem", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "log", None))
        self.b_save_file.setText(_translate("Dialog", "save", None))
        self.b_choose_path.setText(_translate("Dialog", "choose path", None))
        self.label.setText(_translate("Dialog", ".mat", None))
        self.i_file_name.setText(_translate("Dialog", "mat_name", None))
        self.label_3.setText(_translate("Dialog", "Save results to .mat file:", None))
        self.label_6.setText(_translate("Dialog", "Save Ferda\'s state:", None))
        self.i_state_name.setText(_translate("Dialog", "checkpoin_name", None))
        self.label_7.setText(_translate("Dialog", ".plk", None))
        self.b_choose_path_state.setText(_translate("Dialog", "choose path", None))
        self.b_save_state.setText(_translate("Dialog", "save", None))
        self.label_10.setText(_translate("Dialog", "Load Ferda\'s state:", None))
        self.b_load_state.setText(_translate("Dialog", "load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "save", None))
        self.label_11.setText(_translate("Dialog", "avg a_area:", None))
        self.label_12.setText(_translate("Dialog", "avg a_a:", None))
        self.label_13.setText(_translate("Dialog", "mser_thresh:", None))
        self.l_avg_a_area.setText(_translate("Dialog", "0", None))
        self.l_avg_a_a.setText(_translate("Dialog", "0", None))
        self.l_mser_thresh.setText(_translate("Dialog", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("Dialog", "info", None))

