# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ants_init.ui'
#
# Created: Sun May 11 14:17:40 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(429, 611)
        Dialog.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.arena_group = QtGui.QGroupBox(Dialog)
        self.arena_group.setEnabled(False)
        self.arena_group.setGeometry(QtCore.QRect(10, 210, 271, 151))
        self.arena_group.setMinimumSize(QtCore.QSize(251, 111))
        self.arena_group.setAutoFillBackground(False)
        self.arena_group.setFlat(False)
        self.arena_group.setCheckable(False)
        self.arena_group.setObjectName(_fromUtf8("arena_group"))
        self.label_3 = QtGui.QLabel(self.arena_group)
        self.label_3.setGeometry(QtCore.QRect(8, 90, 50, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.arena_x_scrollbar = QtGui.QScrollBar(self.arena_group)
        self.arena_x_scrollbar.setGeometry(QtCore.QRect(74, 31, 160, 16))
        self.arena_x_scrollbar.setSizeIncrement(QtCore.QSize(5, 5))
        self.arena_x_scrollbar.setMaximum(2000)
        self.arena_x_scrollbar.setPageStep(30)
        self.arena_x_scrollbar.setProperty("value", 404)
        self.arena_x_scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.arena_x_scrollbar.setInvertedAppearance(False)
        self.arena_x_scrollbar.setObjectName(_fromUtf8("arena_x_scrollbar"))
        self.arena_y_scrollbar = QtGui.QScrollBar(self.arena_group)
        self.arena_y_scrollbar.setGeometry(QtCore.QRect(74, 61, 160, 16))
        self.arena_y_scrollbar.setMaximum(2000)
        self.arena_y_scrollbar.setProperty("value", 386)
        self.arena_y_scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.arena_y_scrollbar.setObjectName(_fromUtf8("arena_y_scrollbar"))
        self.label = QtGui.QLabel(self.arena_group)
        self.label.setGeometry(QtCore.QRect(7, 32, 61, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.arena_group)
        self.label_2.setGeometry(QtCore.QRect(4, 61, 70, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.arena_r_scrollbar = QtGui.QScrollBar(self.arena_group)
        self.arena_r_scrollbar.setGeometry(QtCore.QRect(74, 91, 160, 16))
        self.arena_r_scrollbar.setMaximum(1000)
        self.arena_r_scrollbar.setPageStep(3)
        self.arena_r_scrollbar.setProperty("value", 383)
        self.arena_r_scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.arena_r_scrollbar.setObjectName(_fromUtf8("arena_r_scrollbar"))
        self.label_r = QtGui.QLabel(self.arena_group)
        self.label_r.setGeometry(QtCore.QRect(240, 90, 34, 17))
        self.label_r.setObjectName(_fromUtf8("label_r"))
        self.label_x = QtGui.QLabel(self.arena_group)
        self.label_x.setGeometry(QtCore.QRect(240, 30, 34, 17))
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.label_y = QtGui.QLabel(self.arena_group)
        self.label_y.setGeometry(QtCore.QRect(240, 60, 34, 17))
        self.label_y.setObjectName(_fromUtf8("label_y"))
        self.b_continue_arena = QtGui.QPushButton(self.arena_group)
        self.b_continue_arena.setGeometry(QtCore.QRect(100, 120, 161, 27))
        self.b_continue_arena.setObjectName(_fromUtf8("b_continue_arena"))
        self.ants_group = QtGui.QGroupBox(Dialog)
        self.ants_group.setEnabled(False)
        self.ants_group.setGeometry(QtCore.QRect(10, 370, 271, 101))
        self.ants_group.setObjectName(_fromUtf8("ants_group"))
        self.label_4 = QtGui.QLabel(self.ants_group)
        self.label_4.setGeometry(QtCore.QRect(15, 25, 121, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ant_number_spin_box = QtGui.QSpinBox(self.ants_group)
        self.ant_number_spin_box.setGeometry(QtCore.QRect(130, 20, 61, 27))
        self.ant_number_spin_box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ant_number_spin_box.setKeyboardTracking(False)
        self.ant_number_spin_box.setMinimum(1)
        self.ant_number_spin_box.setMaximum(30)
        self.ant_number_spin_box.setProperty("value", 15)
        self.ant_number_spin_box.setObjectName(_fromUtf8("ant_number_spin_box"))
        self.b_continue_ants = QtGui.QPushButton(self.ants_group)
        self.b_continue_ants.setGeometry(QtCore.QRect(100, 50, 161, 27))
        self.b_continue_ants.setObjectName(_fromUtf8("b_continue_ants"))
        self.ants_selection_group = QtGui.QGroupBox(Dialog)
        self.ants_selection_group.setEnabled(False)
        self.ants_selection_group.setGeometry(QtCore.QRect(290, 0, 141, 611))
        self.ants_selection_group.setObjectName(_fromUtf8("ants_selection_group"))
        self.verticalLayoutWidget = QtGui.QWidget(self.ants_selection_group)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 131, 551))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.ants_selection_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.ants_selection_layout.setSpacing(0)
        self.ants_selection_layout.setMargin(0)
        self.ants_selection_layout.setObjectName(_fromUtf8("ants_selection_layout"))
        self.start_button = QtGui.QPushButton(self.ants_selection_group)
        self.start_button.setGeometry(QtCore.QRect(0, 578, 130, 28))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.video_group = QtGui.QGroupBox(Dialog)
        self.video_group.setGeometry(QtCore.QRect(10, 10, 271, 201))
        self.video_group.setMinimumSize(QtCore.QSize(251, 111))
        self.video_group.setAutoFillBackground(False)
        self.video_group.setFlat(False)
        self.video_group.setCheckable(False)
        self.video_group.setObjectName(_fromUtf8("video_group"))
        self.file_name_label = QtGui.QLabel(self.video_group)
        self.file_name_label.setGeometry(QtCore.QRect(3, 23, 261, 14))
        self.file_name_label.setObjectName(_fromUtf8("file_name_label"))
        self.b_choose_video = QtGui.QPushButton(self.video_group)
        self.b_choose_video.setGeometry(QtCore.QRect(0, 41, 141, 29))
        self.b_choose_video.setObjectName(_fromUtf8("b_choose_video"))
        self.ch_invert_image = QtGui.QCheckBox(self.video_group)
        self.ch_invert_image.setEnabled(False)
        self.ch_invert_image.setGeometry(QtCore.QRect(2, 100, 110, 20))
        self.ch_invert_image.setChecked(False)
        self.ch_invert_image.setObjectName(_fromUtf8("ch_invert_image"))
        self.b_load_video = QtGui.QPushButton(self.video_group)
        self.b_load_video.setEnabled(False)
        self.b_load_video.setGeometry(QtCore.QRect(150, 42, 110, 27))
        self.b_load_video.setObjectName(_fromUtf8("b_load_video"))
        self.b_video_continue = QtGui.QPushButton(self.video_group)
        self.b_video_continue.setEnabled(False)
        self.b_video_continue.setGeometry(QtCore.QRect(134, 170, 120, 27))
        self.b_video_continue.setObjectName(_fromUtf8("b_video_continue"))
        self.label_5 = QtGui.QLabel(self.video_group)
        self.label_5.setGeometry(QtCore.QRect(5, 80, 241, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.b_count_bg_model = QtGui.QPushButton(self.video_group)
        self.b_count_bg_model.setEnabled(False)
        self.b_count_bg_model.setGeometry(QtCore.QRect(6, 130, 250, 27))
        self.b_count_bg_model.setObjectName(_fromUtf8("b_count_bg_model"))
        self.b_use_model = QtGui.QPushButton(self.video_group)
        self.b_use_model.setEnabled(False)
        self.b_use_model.setGeometry(QtCore.QRect(4, 170, 120, 27))
        self.b_use_model.setObjectName(_fromUtf8("b_use_model"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "experiment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.arena_group.setTitle(QtGui.QApplication.translate("Dialog", "Arena", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "middle X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", " middle Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_r.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b_continue_arena.setText(QtGui.QApplication.translate("Dialog", "confirm and continue", None, QtGui.QApplication.UnicodeUTF8))
        self.ants_group.setTitle(QtGui.QApplication.translate("Dialog", "Ants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Number of ants:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_continue_ants.setText(QtGui.QApplication.translate("Dialog", "confirm and continue", None, QtGui.QApplication.UnicodeUTF8))
        self.ants_selection_group.setTitle(QtGui.QApplication.translate("Dialog", "Ants selection", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("Dialog", "confirm and start", None, QtGui.QApplication.UnicodeUTF8))
        self.video_group.setTitle(QtGui.QApplication.translate("Dialog", "Video source", None, QtGui.QApplication.UnicodeUTF8))
        self.file_name_label.setText(QtGui.QApplication.translate("Dialog", "source path...", None, QtGui.QApplication.UnicodeUTF8))
        self.b_choose_video.setText(QtGui.QApplication.translate("Dialog", "choose video file", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_invert_image.setText(QtGui.QApplication.translate("Dialog", "invert image", None, QtGui.QApplication.UnicodeUTF8))
        self.b_load_video.setText(QtGui.QApplication.translate("Dialog", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.b_video_continue.setText(QtGui.QApplication.translate("Dialog", "without model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "if ants are light on dark background", None, QtGui.QApplication.UnicodeUTF8))
        self.b_count_bg_model.setText(QtGui.QApplication.translate("Dialog", "count bg model (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_use_model.setText(QtGui.QApplication.translate("Dialog", "use model", None, QtGui.QApplication.UnicodeUTF8))

